manifest:
  remotes:
    - name: ali
      url-base: https://github.com/ali
  projects:
    - name: zmk
      remote: ali
      revision: feat/battery-reporting
      import: app/west.yml
  self:
    path: config
